version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: synoms
      POSTGRES_PASSWORD: synoms
      PGDATA: /data/postgres
    volumes:
      - postgres:/var/lib/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: synoms
      MONGO_INITDB_ROOT_PASSWORD: synoms
    ports:
      - "27017:27017"
    networks:
      - mongo
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

# Networks
# networks:
# TODO:




# Volumes
volumes:
  postgres: