server:
  port: 8084
spring:
  application:
    name: media-service

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 2KB
  data:
    mongodb:
      authentication-database: admin
      username: synoms
      password: synoms
      database: products
      host: mongodb
      port: 27017
      uri: mongodb://synoms:synoms@localhost:27017/
      auto-index-creation: true
