spring:
  application:
    name: user
  datasource:
    username: synoms
    password: synoms
    url: jdbc:postgresql://localhost:5432/USER
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    